import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "./script.js";
import NavBar from "@/components/layouts/Header";
import Footer from "@/components/layouts/Footer";
import SocialIcons from "@/components/layouts/SocialIcons";
import ScrollToTopButton from "@/components/layouts/ScrollToTopButton";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
   icons: {
    icon: "/images/favicon.jpg",
  },
  title: "Code Nest 24",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
        <NavBar/>
        <main className="min-h-screen">
           {children}
        </main>
        <Footer/>
        <SocialIcons/>
        <ScrollToTopButton/>
      </body>
    </html>
  );
}
